spring:
  application:
    name: xiaozhi
  profiles:
    include: secret
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_db
  datasource:
    url: jdbc:mysql://localhost:3306/guiguxiaozhi
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
langchain4j:
  open-ai:
    chat-model:
      base-url: http://langchain4j.dev/demo/openai/v1
      api-key: ${openai.api.key}
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: qwen3:0.6b
      temperature: 0.2
      timeout: PT60S
      log-requests: true
      log-responses: true
  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-max
logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl