spring:
  application:
    name: xiaozhi
  profiles:
    include: secret
langchain4j:
  open-ai:
    chat-model:
      base-url: http://langchain4j.dev/demo/openai/v1
      api-key: ${openai.api.key}
      model-name: gpt-4o-mini
      log-requests: true
      log-responses: true
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: qwen3:0.6b
      temperature: 0.2
      timeout: PT60S